#if DEVELOPMENT_BUILD || UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.EventSystems;
using Kamilunavo.RisingSteps.Core;
using Kamilunavo.RisingSteps.Gameplay;
using Kamilunavo.RisingSteps.UI;
namespace Kamilunavo.RisingSteps.QA
{
 public sealed class RisingRuntimeQa:MonoBehaviour
 {
  private RisingCourse _course;private RisingHud _hud;private PlayerMotor _motor;private string _out;private int _checks;private static bool Enabled=>Array.Exists(Environment.GetCommandLineArgs(),a=>a=="-qaRising")||Environment.GetEnvironmentVariable("RISING_QA")=="1";
  public static void Configure(){if(Enabled)RisingSave.QaKey="kamilunavo.risingsteps.qa."+(Environment.GetEnvironmentVariable("RISING_QA_ID")??"local");}
  public static void MaybeStart(RisingCourse course,RisingHud hud,PlayerMotor motor){if(!Enabled)return;var qa=new GameObject("RisingRuntimeQa").AddComponent<RisingRuntimeQa>();qa._course=course;qa._hud=hud;qa._motor=motor;qa.StartCoroutine(qa.Run());}
  private static string Arg(string name,string fallback){var args=Environment.GetCommandLineArgs();int i=Array.IndexOf(args,name);return i>=0&&i+1<args.Length?args[i+1]:fallback;}
  private void Check(bool value,string name){_checks++;if(value){Debug.Log("QA_PASS "+name);return;}File.WriteAllText(Path.Combine(_out,"FAIL.txt"),name);Debug.LogError("RISING_QA_FAIL "+name);throw new Exception(name);}
  private IEnumerator Capture(string name){yield return new WaitForEndOfFrame();var image=ScreenCapture.CaptureScreenshotAsTexture();try{File.WriteAllBytes(Path.Combine(_out,name+".png"),image.EncodeToPNG());}finally{Destroy(image);}yield return null;}
  private IEnumerator Run(){_out=Arg("-qaOutput",Path.Combine(Application.persistentDataPath,"RisingQA"));Directory.CreateDirectory(_out);yield return new WaitForSecondsRealtime(1);
   Check(_hud.ModalOpen&&_course.Paused,"initial home paused");yield return Capture("home");
   if(Environment.GetEnvironmentVariable("RISING_QA_TUTORIAL")=="1"){yield return TutorialAndHome();File.WriteAllText(Path.Combine(_out,"PASS.txt"),"RISING_TUTORIAL_PASS "+_checks);Debug.Log("RISING_TUTORIAL_PASS "+_checks);yield break;}
   if(Environment.GetEnvironmentVariable("RISING_QA_RELOAD")=="1"){Check(_course.Height>0,"saved non-origin step restored on fresh native boot");Check(Vector3.Distance(_motor.transform.position,_course.SafePosition)<.12f,"fresh boot puts actual controller at saved island");yield return Capture("restored-checkpoint");File.WriteAllText(Path.Combine(_out,"RELOAD-PASS.txt"),"Fresh native bootstrap restored step="+_course.Height+" realm="+_course.Profile.Realm+" safe="+_course.SafePosition);Debug.Log("RISING_RELOAD_PASS step="+_course.Height);yield break;}
_hud.Close();_course.StartRun(0,false);yield return new WaitForSeconds(.5f);
   if(Environment.GetEnvironmentVariable("RISING_QA_CAMERA")=="1"){yield return CameraTouchOwnership();yield return CameraFeedback();File.WriteAllText(Path.Combine(_out,"PASS.txt"),"RISING_CAMERA_PASS "+_checks);Debug.Log("RISING_CAMERA_PASS "+_checks);yield break;}
   var center=new Vector2(Screen.width*.55f,Screen.height*.55f);var e=new PointerEventData(EventSystem.current){position=center};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(e,hits);Check(hits.Count==0,"world route does not intercept camera input");
   _motor.Jump.OnPointerDown(e);_hud.ShowSettings();float before=_course.Profile.Elapsed;yield return new WaitForSeconds(.15f);Check(Mathf.Abs(before-_course.Profile.Elapsed)<.01f&&_motor.Paused,"modal pauses motor and timer");_hud.Close();Check(!_motor.Jump.Consume(),"modal clears stale jump");
   _motor.Jump.OnPointerDown(e);float focusTime=_course.Profile.Elapsed;_course.SendMessage("OnApplicationFocus",false);yield return new WaitForSeconds(.12f);Check(_motor.Paused&&_course.Profile.Elapsed==focusTime&&!_motor.Jump.Consume(),"runtime focus-loss callback pauses timer and clears jump");_course.SendMessage("OnApplicationPause",true);_course.SendMessage("OnApplicationFocus",true);Check(_motor.Paused,"focus return does not override application pause");_course.SendMessage("OnApplicationPause",false);Check(!_motor.Paused,"runtime lifecycle callbacks resume after both return");
   var jr=(RectTransform)_hud.Joystick.transform;Vector2 jc=RectTransformUtility.WorldToScreenPoint(null,jr.TransformPoint(jr.rect.center));var first=new PointerEventData(EventSystem.current){pointerId=100,position=jc+Vector2.up*35};_hud.Joystick.OnPointerDown(first);Vector2 value=_hud.Joystick.Value;var other=new PointerEventData(EventSystem.current){pointerId=101,position=jc+Vector2.right*35};_hud.Joystick.OnPointerDown(other);_hud.Joystick.OnPointerUp(other);Check(_hud.Joystick.Value==value,"second finger cannot steal joystick");_hud.Joystick.OnPointerUp(first);
   if(Environment.GetEnvironmentVariable("RISING_QA_QUICK")=="1"){for(int restart=0;restart<5;restart++){_course.StartRun(0,false);yield return Climb(1);Check(_course.Profile.Falls==0,"quick restart no fall "+restart);}Debug.Log("RISING_QUICK_PASS");yield break;}
   for(int realm=0;realm<3;realm++){_course.StartRun(realm,false);yield return new WaitForSeconds(.5f);
    var scenery=_course.transform.Find("RealmScenery"+realm);Check(scenery!=null&&scenery.gameObject.activeInHierarchy,"selected realm owns current scenery "+realm);
    Check(_course.GetComponentsInChildren<Transform>().Length>0&&scenery.GetComponentsInChildren<Transform>().Length>0,"realm scenery has authored geometry "+realm);
    Check(scenery.Find(realm==1?"DistantCascade":realm==2?"DistantTemple":"DistantMeadow")!=null,"selected realm changes distant island architecture "+realm);
    Check(Array.Exists(scenery.GetComponentsInChildren<Transform>(),t=>t.name==(realm==1?"CascadePool":realm==2?"TempleColumn":"WindTree")),"selected realm contains unique visible landmarks "+realm);
    Check(_course.GetComponentsInChildren<Kamilunavo.RisingSteps.Visuals.CloudBillboard>().Length==9,"world selection replaces cloud scenery instead of accumulating it");
    yield return Capture("realm"+realm+"-start");for(int step=1;step<=12;step++){yield return Climb(step);yield return Capture("realm"+realm+"-step"+step);}
    yield return WalkTo(_course.Steps[12].transform.position+Vector3.forward*.5f,2);yield return new WaitForSeconds(.2f);Check(_course.Profile.Completed&&_hud.ModalOpen,"actual portal completion realm"+realm);Check(_course.Profile.Stars[realm]>0,"realm stars saved");_hud.Close();}
   Check(Mathf.Abs(_motor.CameraTransform.GetComponent<Kamilunavo.RisingSteps.CameraSystem.OrbitCamera>().Yaw)<.01f,"player movement never forces camera yaw");
   var saved=RisingSave.Load();Check(saved.Step==12&&saved.Completed&&saved.UnlockedRealm==2,"saved checkpoint/realm completion");
   _course.StartRun(0,false);yield return Climb(1);Check(_course.Profile.Falls==0,"new route starts without an uncommanded fall");_motor.ResetInput();int fallsBefore=_course.Profile.Falls;float fallStart=Time.realtimeSinceStartup;Drive(Vector3.right,true);
   while(_course.Profile.Falls==fallsBefore&&Time.realtimeSinceStartup-fallStart<8){Drive(Vector3.right);yield return null;}_motor.ResetInput();yield return new WaitForSeconds(.15f);
   Check(_course.Profile.Falls==fallsBefore+1&&Vector3.Distance(_motor.transform.position,_course.SafePosition)<1,"natural fall recovers checkpoint fallsBefore="+fallsBefore+" falls="+_course.Profile.Falls+" player="+_motor.transform.position+" safe="+_course.SafePosition+" paused="+_course.Paused);
   int coins=_course.Profile.Crystals;bool claim=_course.ClaimDaily();int after=_course.Profile.Crystals;_course.ClaimDaily();Check(after==_course.Profile.Crystals&&(!claim||after>=coins+100),"daily guard runtime");_hud.ShowDaily();yield return Capture("daily");_hud.ShowStyle();yield return Capture("style");_hud.ShowShop();yield return Capture("shop");CheckModalTargets("portrait shop");Check(!_course.Store.Ready&&!_course.Store.CanBuy(Kamilunavo.RisingSteps.Monetization.CommerceRules.Starter),"QA store unavailable does not offer a fake purchase");_hud.ShowSettings();yield return Capture("settings");_hud.Close();yield return Capture("gameplay");CheckControls("portrait");
   Screen.orientation=ScreenOrientation.LandscapeLeft;yield return WaitOrientation(true);CheckControls("landscape");yield return Capture("landscape");_hud.ShowAchievements();yield return new WaitForSeconds(.2f);CheckModalTargets("landscape achievements");yield return CheckModalScroll();yield return Capture("landscape-achievements");_hud.Close();
   ReservedRegionProvider.QaDivision=new Rect(.48f,0,.04f,1);yield return new WaitForSeconds(.3f);CheckControls("reserved pane");Check(Camera.main.rect.xMax<=.481f||Camera.main.rect.xMin>=.519f,"camera avoids vertical division on either usable pane rect="+Camera.main.rect);yield return Capture("reserved-pane");ReservedRegionProvider.QaDivision=null;
   Screen.orientation=ScreenOrientation.Portrait;yield return WaitOrientation(false);CheckControls("restored portrait");
   if(Array.Exists(Environment.GetCommandLineArgs(),a=>a=="-qaRisingSoak")||Environment.GetEnvironmentVariable("RISING_QA_SOAK")=="1")yield return Soak();
   File.WriteAllText(Path.Combine(_out,"PASS.txt"),"RISING_QA_PASS checks="+_checks+" actual controller 36 steps and natural fall; isolated save; no FPS claim");Debug.Log("RISING_QA_PASS checks="+_checks);
   if(Array.Exists(Environment.GetCommandLineArgs(),a=>a=="-qaExit"))Application.Quit();
  }
  private IEnumerator WaitOrientation(bool landscape){
   // Desktop orientation requests do not rotate a window; exercise the actual
   // landscape layout before asserting that its clipped content can scroll.
   if(!Application.isMobilePlatform)Screen.SetResolution(landscape?956:540,landscape?440:960,false);
   float start=Time.realtimeSinceStartup;while((Screen.width>Screen.height)!=landscape&&Time.realtimeSinceStartup-start<4)yield return null;
#if UNITY_IOS && !UNITY_EDITOR
   Check((Screen.width>Screen.height)==landscape,"native orientation settled "+(landscape?"landscape":"portrait")+" "+Screen.width+"x"+Screen.height);
#endif
   yield return new WaitForSeconds(.15f);
  }
  private void CheckControls(string pose){var controls=new[]{(RectTransform)_hud.Joystick.transform,(RectTransform)_hud.Jump.transform,(RectTransform)GameObject.Find("Menu").transform,(RectTransform)_hud.Look.transform};Rect view=Camera.main.pixelRect;foreach(var control in controls){var rect=UiMetrics.ScreenRect(control);Check(rect.width/UiMetrics.PointScale>=48&&rect.height/UiMetrics.PointScale>=48,pose+" minimum48 points "+control.name+" rect="+rect+" pointScale="+UiMetrics.PointScale);Check(view.Contains(rect.min+Vector2.one)&&view.Contains(rect.max-Vector2.one),pose+" control inside usable view "+control.name);}}
  private IEnumerator CheckModalScroll(){Canvas.ForceUpdateCanvases();var close=GameObject.Find("Close");var viewport=(RectTransform)close.transform.parent.Find("Viewport");var scroll=viewport.GetComponent<UnityEngine.UI.ScrollRect>();var rect=UiMetrics.ScreenRect(viewport);var pointer=new PointerEventData(EventSystem.current){pointerId=300,position=rect.center,pressPosition=rect.center};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(pointer,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<UnityEngine.UI.ScrollRect>()==scroll,"description gesture raycasts into scroll hierarchy");float before=scroll.content.anchoredPosition.y;ExecuteEvents.ExecuteHierarchy(hits[0].gameObject,pointer,ExecuteEvents.beginDragHandler);pointer.position+=Vector2.up*Mathf.Min(rect.height*.25f,150);ExecuteEvents.ExecuteHierarchy(hits[0].gameObject,pointer,ExecuteEvents.dragHandler);ExecuteEvents.ExecuteHierarchy(hits[0].gameObject,pointer,ExecuteEvents.endDragHandler);yield return null;Check(scroll.content.anchoredPosition.y>before+.1f,"actual description drag scrolls clipped achievements");}
  private void CheckModalTargets(string pose){var close=GameObject.Find("Close");if(close==null)return;var rect=UiMetrics.ScreenRect((RectTransform)close.transform);Check(rect.height/UiMetrics.PointScale>=47.999f&&rect.width/UiMetrics.PointScale>=47.999f,pose+" close >=48 logical points");var viewport=close.transform.parent.Find("Viewport");Check(viewport.GetComponent<UnityEngine.UI.Image>().raycastTarget,pose+" text viewport accepts scroll gestures");}
  private IEnumerator Soak(){float start=Time.realtimeSinceStartup,next=0;int phase=0;long startMemory=UnityEngine.Profiling.Profiler.GetTotalAllocatedMemoryLong(),peakMemory=startMemory;var frames=new List<float>();var errors=new List<string>();Application.LogCallback handler=(message,stack,type)=>{if(type==LogType.Exception||type==LogType.Error||type==LogType.Assert)errors.Add(message);};Application.logMessageReceived+=handler;
   while(Time.realtimeSinceStartup-start<1800){if(Time.realtimeSinceStartup-start>=next){next+=60;phase++;_hud.Close();ReservedRegionProvider.QaDivision=null;Screen.orientation=phase%2==0?ScreenOrientation.Portrait:ScreenOrientation.LandscapeLeft;_course.StartRun(phase%3,false);if(phase%5==0)_hud.ShowStyle();if(phase%5==1)_hud.ShowDaily();if(phase%5==2)_hud.ShowSettings();if(phase%5==3)ReservedRegionProvider.QaDivision=new Rect(.48f,0,.04f,1);if(phase%5==4){yield return Climb(1);yield return Climb(2);}yield return Capture("soak-phase"+phase);}
    peakMemory=Math.Max(peakMemory,UnityEngine.Profiling.Profiler.GetTotalAllocatedMemoryLong());frames.Add(Time.unscaledDeltaTime*1000);yield return null;}
   Application.logMessageReceived-=handler;ReservedRegionProvider.QaDivision=null;frames.Sort();float elapsed=Time.realtimeSinceStartup-start;int p95=Mathf.Clamp(Mathf.FloorToInt(frames.Count*.95f),0,frames.Count-1);File.WriteAllText(Path.Combine(_out,"soak.json"),"{\"elapsedSeconds\":"+elapsed.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"frames\":"+frames.Count+",\"p95FrameMs\":"+frames[p95].ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"startAllocatedBytes\":"+startMemory+",\"endAllocatedBytes\":"+UnityEngine.Profiling.Profiler.GetTotalAllocatedMemoryLong()+",\"peakAllocatedBytes\":"+peakMemory+",\"errors\":"+errors.Count+",\"note\":\"simulator/host rendering only; not physical device thermal acceptance\"}");Check(elapsed>=1800&&errors.Count==0,"30-minute real-time rendering soak");
  }
  private static void Pointer(GameObject target,PointerEventData pointer,ExecuteEvents.EventFunction<IPointerDownHandler> callback)=>ExecuteEvents.ExecuteHierarchy(target,pointer,callback);
  private GameObject Hit(RectTransform rect,PointerEventData pointer){pointer.position=UiMetrics.ScreenRect(rect).center;var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(pointer,hits);Check(hits.Count>0,"real UI raycast owns "+rect.name);return hits[0].gameObject;}
  private IEnumerator CameraTouchOwnership(){
   var orbit=_motor.CameraTransform.GetComponent<Kamilunavo.RisingSteps.CameraSystem.OrbitCamera>();orbit.ResetView();Canvas.ForceUpdateCanvases();
   var move=new PointerEventData(EventSystem.current){pointerId=11};var movement=Hit((RectTransform)_hud.Joystick.transform,move);Pointer(movement,move,ExecuteEvents.pointerDownHandler);move.position+=Vector2.up*35;ExecuteEvents.ExecuteHierarchy(movement,move,ExecuteEvents.dragHandler);
   var jump=new PointerEventData(EventSystem.current){pointerId=22};var jumpTarget=Hit((RectTransform)_hud.Jump.transform,jump);Pointer(jumpTarget,jump,ExecuteEvents.pointerDownHandler);
   float yaw=orbit.Yaw;var foreign=new PointerEventData(EventSystem.current){pointerId=22,position=UiMetrics.ScreenRect((RectTransform)_hud.Look.transform).center};ExecuteEvents.ExecuteHierarchy(_hud.Look.gameObject,foreign,ExecuteEvents.dragHandler);
   var held=_hud.Joystick.Value;yield return new WaitForEndOfFrame();Check(orbit.Yaw==yaw&&_hud.Joystick.Value==held,"movement+jump finger dragged across View cannot orbit or steal movement");
   var deliberate=new PointerEventData(EventSystem.current){pointerId=33};var lookTarget=Hit((RectTransform)_hud.Look.transform,deliberate);Pointer(lookTarget,deliberate,ExecuteEvents.pointerDownHandler);deliberate.position+=Vector2.right*40*UiMetrics.PointScale;ExecuteEvents.ExecuteHierarchy(lookTarget,deliberate,ExecuteEvents.dragHandler);Check(orbit.Yaw>yaw,"deliberate View owner rotates while movement held");float requested=orbit.Yaw;
   ExecuteEvents.ExecuteHierarchy(lookTarget,foreign,ExecuteEvents.pointerUpHandler);deliberate.position+=Vector2.right*20*UiMetrics.PointScale;ExecuteEvents.ExecuteHierarchy(lookTarget,deliberate,ExecuteEvents.dragHandler);Check(orbit.Yaw>requested,"jump finger release cannot release View owner");
   _hud.ShowSettings();requested=orbit.Yaw;_hud.Close();deliberate.position+=Vector2.right*40*UiMetrics.PointScale;ExecuteEvents.ExecuteHierarchy(lookTarget,deliberate,ExecuteEvents.dragHandler);Check(orbit.Yaw==requested,"modal invalidates View ownership after resume");_motor.ResetInput();_course.StartRun(0,false);yield return new WaitForSeconds(.4f);Check(orbit.Yaw==0,"new route faces forward again");yield return Capture("deliberate-camera-ownership");
  }
  private IEnumerator TutorialAndHome(){
   var canvas=_hud.Joystick.GetComponentInParent<Canvas>();var primary=canvas.transform.Find("SafeArea/ModalBackdrop/ModalCard/Close").GetComponent<UnityEngine.UI.Button>();Check(primary.GetComponentInChildren<UnityEngine.UI.Text>().text.Length>0,"home has a concrete primary play action");
   var content=canvas.transform.Find("SafeArea/ModalBackdrop/ModalCard/Viewport/Content");Check(content.Find("SkyAtlas")!=null&&content.Find("Realm0/RealmArt")!=null&&content.Find("Realm1/RealmArt")!=null&&content.Find("Realm2/RealmArt")!=null,"home has hero atlas and three illustrated realm previews");
   int initialCoins=_course.Profile.Crystals;primary.onClick.Invoke();var tutorial=_hud.GetComponent<RisingTutorial>();Check(tutorial.Active&&!_course.Paused&&!_hud.ModalOpen,"first play enters actual playable tutorial");yield return Capture("tutorial-move");
   Drive(Vector3.forward,true);float start=Time.realtimeSinceStartup;while(tutorial.Stage==0&&Time.realtimeSinceStartup-start<2)yield return null;Check(tutorial.Stage==1,"actual joystick movement advances tutorial");yield return Capture("tutorial-jump");_motor.ResetInput();
   yield return Climb(1);Check(!tutorial.Active&&_course.Profile.TutorialDone,"actual jump and first ordered landing complete tutorial");Check(RisingSave.Load().TutorialDone,"tutorial completion survives save reload");Check(_course.Profile.Crystals==initialCoins+12+(_course.Profile.Perfects==1?5:0),"tutorial only grants ordinary first landing reward");yield return Capture("tutorial-complete");
   int coins=_course.Profile.Crystals,step=_course.Height;_hud.ReplayTutorial();Check(tutorial.Active&&_course.Height==step&&_course.Profile.Crystals==coins,"tutorial replay preserves checkpoint and crystal balance");yield return Capture("tutorial-replay");tutorial.Finish();Check(!tutorial.Active&&RisingSave.Load().TutorialDone,"tutorial skip persists");
   _hud.ShowHome();yield return Capture("home-progress");var homeScroll=canvas.transform.Find("SafeArea/ModalBackdrop/ModalCard/Viewport").GetComponent<UnityEngine.UI.ScrollRect>();homeScroll.verticalNormalizedPosition=0;yield return new WaitForSecondsRealtime(.2f);yield return Capture("home-actions");_hud.ShowStyle();yield return Capture("style-refreshed");_hud.ShowHome();yield return null;_hud.Close();
  }
  private IEnumerator CameraFeedback(){
   var orbit=_motor.CameraTransform.GetComponent<Kamilunavo.RisingSteps.CameraSystem.OrbitCamera>();
   var pitchField=typeof(Kamilunavo.RisingSteps.CameraSystem.OrbitCamera).GetField("_pitch",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);
   var yawField=typeof(Kamilunavo.RisingSteps.CameraSystem.OrbitCamera).GetField("_yaw",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);
   var cases=new[]{new Vector2(0,1),new Vector2(.55f,.8f),new Vector2(-.55f,.8f),new Vector2(0,1),new Vector2(.55f,.8f),new Vector2(-.55f,.8f)};
   for(int scenario=0;scenario<cases.Length;scenario++){
    _motor.ResetInput();_course.StartRun(0,false);yawField.SetValue(orbit,scenario==2?35f:0f);yield return new WaitForSecondsRealtime(.6f);
    Canvas.ForceUpdateCanvases();var rect=(RectTransform)_hud.Joystick.transform;
    var jumpRect=(RectTransform)_hud.Jump.transform;var jumpCenter=RectTransformUtility.WorldToScreenPoint(null,jumpRect.TransformPoint(jumpRect.rect.center));
    var raycasts=new List<RaycastResult>();EventSystem.current.RaycastAll(new PointerEventData(EventSystem.current){position=jumpCenter},raycasts);
    Check(raycasts.Count>0&&raycasts[0].gameObject.GetComponentInParent<Kamilunavo.RisingSteps.Input.PressButton>()==_hud.Jump,"jump center top raycast belongs to actual jump UI");var actualJumpTarget=raycasts[0].gameObject;
    var local=rect.rect.center+cases[scenario]*Mathf.Min(rect.rect.width,rect.rect.height)*.5f;
    // A real finger starts inside the pad and can then drag to its full-radius
    // edge. A Began exactly at yMax is outside a half-open rectangle on native.
    var downLocal=rect.rect.center+(local-rect.rect.center)*.75f;
    var pointer=new PointerEventData(EventSystem.current){pointerId=220,position=RectTransformUtility.WorldToScreenPoint(null,rect.TransformPoint(downLocal))};
    raycasts.Clear();EventSystem.current.RaycastAll(pointer,raycasts);var boundary=RectTransformUtility.WorldToScreenPoint(null,rect.TransformPoint(local));Debug.Log("RISING_CAMERA_TOUCH_SAMPLE scenario="+scenario+" down="+pointer.position+" fullRadiusBoundary="+boundary+" rect="+UiMetrics.ScreenRect(rect)+" contains="+RectTransformUtility.RectangleContainsScreenPoint(rect,pointer.position,null)+" tutorialActive="+_hud.GetComponent<RisingTutorial>().Active+" hits="+string.Join(",",raycasts.ConvertAll(hit=>hit.gameObject.name)));
    Check(raycasts.Count>0&&raycasts[0].gameObject.GetComponentInParent<Kamilunavo.RisingSteps.Input.VirtualJoystick>()==_hud.Joystick,"joystick interior top raycast belongs to actual joystick UI");var actualMoveTarget=raycasts[0].gameObject;
    Check(_motor.Grounded,"camera probe begins on real collider");float startY=_motor.transform.position.y;
    if(scenario>=3)Pointer(actualJumpTarget,new PointerEventData(EventSystem.current){position=jumpCenter,pointerId=221},ExecuteEvents.pointerDownHandler);
    Pointer(actualMoveTarget,pointer,ExecuteEvents.pointerDownHandler);pointer.position=boundary;ExecuteEvents.ExecuteHierarchy(actualMoveTarget,pointer,ExecuteEvents.dragHandler);var held=_hud.Joystick.Value;
    if(scenario<3){for(int heldFrame=0;heldFrame<5;heldFrame++)yield return new WaitForEndOfFrame();Pointer(actualJumpTarget,new PointerEventData(EventSystem.current){position=jumpCenter,pointerId=221},ExecuteEvents.pointerDownHandler);}
    float maxYaw=0,maxPitch=0;bool rose=false;var trace=new System.Text.StringBuilder("frame,storedYaw,renderYaw,storedPitch,renderPitch,x,y,z,joyX,joyY\n");
    for(int frame=0;frame<18;frame++){yield return new WaitForEndOfFrame();float pitch=(float)pitchField.GetValue(orbit);var angles=_motor.CameraTransform.eulerAngles;maxYaw=Mathf.Max(maxYaw,Mathf.Abs(Mathf.DeltaAngle(orbit.Yaw,angles.y)));maxPitch=Mathf.Max(maxPitch,Mathf.Abs(Mathf.DeltaAngle(pitch,angles.x)));rose|=_motor.transform.position.y>startY+.05f;Check((_hud.Joystick.Value-held).sqrMagnitude<.000001f,"actual joystick unchanged during jump frame"+frame);var pos=_motor.transform.position;trace.AppendLine(string.Join(",",frame,orbit.Yaw,angles.y,pitch,angles.x,pos.x,pos.y,pos.z,held.x,held.y));}
    File.WriteAllText(Path.Combine(_out,"camera-fixed-thumb-"+scenario+".csv"),trace.ToString());yield return Capture("camera-fixed-thumb-"+scenario);_motor.ResetInput();
    Check(rose,"actual CharacterController jump occurred");Debug.Log("RISING_CAMERA_MEASURE scenario="+scenario+" maxRenderedYawDrift="+maxYaw+" maxRenderedPitchDrift="+maxPitch);
    Check(maxYaw<.05f&&maxPitch<.05f,"jump/follow never alters rendered player-owned camera angles scenario"+scenario+" yaw="+maxYaw+" pitch="+maxPitch);
   }
  }
  private void Drive(Vector3 direction,bool start=false){direction.y=0;var f=_motor.CameraTransform.forward;f.y=0;f.Normalize();var r=_motor.CameraTransform.right;r.y=0;r.Normalize();var axis=new Vector2(Vector3.Dot(direction.normalized,r),Vector3.Dot(direction.normalized,f));var rect=(RectTransform)_hud.Joystick.transform;var local=rect.rect.center+(Vector2)axis*Mathf.Min(rect.rect.width,rect.rect.height)*.5f;var ev=new PointerEventData(EventSystem.current){pointerId=200,position=RectTransformUtility.WorldToScreenPoint(null,rect.TransformPoint(local))};if(start)_hud.Joystick.OnPointerDown(ev);else _hud.Joystick.OnDrag(ev);}
  private IEnumerator Climb(int step){var origin=_course.Steps[step-1].transform.position;var target=_course.Steps[step].transform.position;bool jumped=false;float start=Time.realtimeSinceStartup;Drive(target-_motor.transform.position,true);
   while(_course.Height<step&&Time.realtimeSinceStartup-start<6){var delta=target-_motor.transform.position;delta.y=0;if(delta.magnitude<.12f)_hud.Joystick.ResetInput();else{if(_hud.Joystick.Value==Vector2.zero)Drive(delta,true);else Drive(delta);}
    var travel=_motor.transform.position-origin;travel.y=0;if(!jumped&&Vector3.Dot(travel,new Vector3(target.x-origin.x,0,target.z-origin.z).normalized)>.72f&&_motor.Grounded){_hud.Jump.OnPointerDown(new PointerEventData(EventSystem.current));jumped=true;if(step==1&&Environment.GetEnvironmentVariable("RISING_QA_TUTORIAL")=="1")yield return Capture("tutorial-land");}yield return null;}
   _motor.ResetInput();Check(_course.Height==step,"controller lands step"+step+" position="+_motor.transform.position+" grounded="+_motor.Grounded+" jumped="+jumped+" paused="+_course.Paused);yield return new WaitForSeconds(.05f);
  }
  private IEnumerator WalkTo(Vector3 goal,float seconds){float start=Time.realtimeSinceStartup;Drive(goal-_motor.transform.position,true);while(Time.realtimeSinceStartup-start<seconds&&!_course.Profile.Completed){var d=goal-_motor.transform.position;d.y=0;if(d.magnitude<.12f)break;Drive(d);yield return null;}_motor.ResetInput();}
 }
}
#endif
